name: Update Weather Dashboard

on:
  # Run every 4 hours
  schedule:
    - cron: '0 */4 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on push to main (for testing)
  push:
    branches: [ main ]

jobs:
  update-weather:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright asyncio-compat
        playwright install chromium
    
    - name: Copy scraper files to web directory
      run: |
        cp ../weather_scraper.py .
        cp ../generate_index.py .
        cp ../locations.json .
    
    - name: Run weather scraper
      run: |
        python weather_scraper.py
    
    - name: Clean up old screenshots (older than 48 hours)
      run: |
        find screenshots/ -name "*.png" -mtime +2 -delete || true
        find screenshots/ -name "metadata_*.json" -mtime +2 -delete || true
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit and push changes
      run: |
        git add screenshots/ screenshots_index.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update weather screenshots - $(date '+%Y-%m-%d %H:%M UTC')"
          git push
        fi