name: Update Weather Dashboard

# Give GitHub Actions permission to write to the repository
permissions:
  contents: write

on:
  # Run every 4 hours
  schedule:
    - cron: '0 */4 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on push to main (for testing)
  push:
    branches: [ main ]

jobs:
  update-weather:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install chromium
    
    - name: Verify scraper files are present
      run: |
        ls -la weather_scraper.py generate_index.py locations.json
    
    - name: Run weather scraper
      run: |
        python weather_scraper.py
    
    - name: Clean up old screenshots (older than 48 hours)
      run: |
        python cleanup_by_date.py
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit and push changes
      run: |
        git add screenshots/ screenshots_index.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update weather screenshots - $(date '+%Y-%m-%d %H:%M UTC')"
          git push
        fi